### PR TITLE
Add USize and ISize types

### PR DESCRIPTION
**Pull request by shelvacu**
Also relevant "TryFrom" impls

### CODE REVIEW

**Comment by jhpratt** [comment]
Keep in mind that pointer-sized integers can be 16, 32, or 64 bits — this assumes they are always 64. Additionally, please only have the first letter be capitalized to conform with standard casing practice.

**Comment by shelvacu** [comment]
I don't see where any pointer size is assumed, the only `into` impl is `usize` or `isize`, everyithing other type is under `try_into`. The compiler will complain even if you try to convert `usize` into `u128`.

Fixed the capitalization.

**Comment by jhpratt** [comment]
Upon quick glance it does appear that `usize` doesn't implement `Into<u128>`, contrary to my assumption. As such I will review the PR as-is when I get time. I know it's small but I need to get some things done before starting in a new position. My best guess is I'll be able to review this during the gap in RustConf on Tuesday. I will cut a new release once it's merged, though.

**Comment by jhpratt** [comment]
This actually made me realize that `impl TryFrom<I8<…>> for I16<…>` and similar doesn't exist even though it could/should. That's not an issue with this PR, though.

**Pull request merged**
